#ifndef _IDT_HANDLERS_H
#define _IDT_HANDLERS_H


// Interrupt Handlers
extern void DIVISION_ERROR_HANDLER();
extern void RESERVED_HANDLER();
extern void NMI_HANDLER();
extern void BREAK_POINT_HANDLER();
extern void OVERFLOW_HANDLER();
extern void BOUNDS_HANDLER();
extern void INVALID_OPCODE_HANDLER();
extern void DEVICE_NOT_AVAILABLE_HANDLER();
extern void DOUBLE_FAULT_HANDLER();
extern void COPROCESSOR_SEGMENT_OVERRUN_HANDLER();
extern void INVALID_TSS_HANDLER();
extern void SEGMENT_NOT_PRESENT_HANDLER();
extern void STACK_SEGMENT_FAULT_HANDLER();
extern void GENERAL_PROTECTION_HANDLER();
extern void PAGE_FAULT_HANDLER();

extern void MATH_FPU_FAULT_HANDLER();
extern void ALIGNMENT_CHECK_HANDLER();
extern void MACHINE_CHECK_HANDLER();
extern void SIMD_FLOATING_POINT_EXCEPTION_HANDLER();

#endif /* _IDT_HANDLERS_H */
